version: '3'
services:
  redis-server:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: webapp
    restart: unless-stopped
    depends_on:
      - redis-server
    env_file:
      - .env
