version: '3'
services:
  redis-server:
    image: redis
    # container_name: redis-server
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
  webapp:
    image: webapp
    restart: unless-stopped
    ports:
      - "8077:3000"
    depends_on:
      - redis-server
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - MAX_VALUE=1000
      - MIN_ALPHA=0.0
      - MAX_ALPHA=0.8
