version: '3'
services:
  redis-server:
    image: redis
    container_name: redis-server
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: webapp
    restart: unless-stopped
    ports:
      - "8077:3000"
    depends_on:
      - redis-server
    links:
      - redis-server
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis-server
